### 텐서플로우 실행하기

In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant('Hello Tensorflow') # constant 는 상수, 텐서플로우 상수 생성. 변하지 않는 값
print(hello)

sess = tf.Session()
result = sess.run(hello)
print(result)
sess.close()

Tensor("Const:0", shape=(), dtype=string)
b'Hello Tensorflow'


### 계산그래프 만들기

In [3]:
import tensorflow as tf

# 텐서플로우는 형이 같아야 계산 가능
# 노드 생성
node1 = tf.constant(3, tf.float32) # 실수형으로 만들어줌
node2 = tf.constant(4.0)
node3 = tf.add(node1, node2)

In [4]:
print("node1: ", node1)
print("node2: ", node2)
print("node3: ", node3)

node1:  Tensor("Const_1:0", shape=(), dtype=float32)
node2:  Tensor("Const_2:0", shape=(), dtype=float32)
node3:  Tensor("Add:0", shape=(), dtype=float32)


In [5]:
# 세션이 노드를 실행함
session = tf.Session()
print("session.run([node1, node2])", session.run([node1, node2]))
print("session.run(node3)", session.run(node3))

session.close()

session.run([node1, node2]) [3.0, 4.0]
session.run(node3) 7.0


### 텐서플로우 자료형

In [6]:
# 다른 타입으로
a = tf.constant(1, dtype = tf.float32)
print(a)
print(a.shape)
with tf.Session() as session:
    print(session.run(a))

Tensor("Const_3:0", shape=(), dtype=float32)
()
1.0


In [7]:
# 다른 shape으로
a = tf.constant(1, dtype = tf.float32, shape = (1,))
print(a)
print(a.shape)
with tf.Session() as session:
    print(session.run(a))

Tensor("Const_4:0", shape=(1,), dtype=float32)
(1,)
[1.]


In [8]:
# 2차원으로 설정
a = tf.constant(1, dtype = tf.float32, shape = (1,1))
print(a)
print(a.shape)
with tf.Session() as session:
    print(session.run(a))

Tensor("Const_5:0", shape=(1, 1), dtype=float32)
(1, 1)
[[1.]]


### placeholder
* 값을 바꾸기 쉽다

In [9]:
import tensorflow as tf

input_data = [1, 2, 3]
x = tf.placeholder(dtype = tf.float32)

y = x * 2 # 2는 선언이 생략
print("x: ", x)
print("y: ", y)

session = tf.Session()

# 실행할 때 feed_dict를 통해 값을 전달합니다.
result = session.run(y, feed_dict = {x:input_data})
print(result)
session.close()

x:  Tensor("Placeholder:0", dtype=float32)
y:  Tensor("mul:0", dtype=float32)
[2. 4. 6.]


### variable

In [10]:
x = tf.placeholder(dtype = tf.float32)
x_data = [1,2,4]

#초기값: tf.random_normal([1,3], stddev = 0.35)
weights = tf.Variable([3], dtype = tf.float32)
biases = tf.Variable([4], dtype = tf.float32)

y = weights * x + biases

print("x: ", x)
print("weights: ", weights)
print("biases: ", biases)

Instructions for updating:
Colocations handled automatically by placer.
x:  Tensor("Placeholder_1:0", dtype=float32)
weights:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
biases:  <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>


### 개별 initializer

In [11]:
with tf.Session() as session:
    # 초기화 오퍼레이션을 실행
    session.run([weights.initializer, biases.initializer])
    
    result = session.run(y, feed_dict = {x : x_data})
    print(result)
    
    # 변수 변경 // 변수 재 할당
    session.run(tf.assign(weights, [2]))
    
    # 다시 실행
    result = session.run(y, feed_dict = {x : x_data})
    print(result)
    

[ 7. 10. 16.]
[ 6.  8. 12.]


### 전체 변수 한번에 초기화 global_variables_initializer

In [12]:
# 변수 초기화 작업
init_op = tf.global_variables_initializer()

with tf.Session() as session:
    # 초기화 오퍼레이션을 실행
    session.run(init_op)
    
    result = session.run(y, feed_dict = {x : x_data})
    print(result)
    
    # 변수 변경 // 변수 재 할당
    session.run(tf.assign(weights, [2]))
    
    # 다시 실행
    result = session.run(y, feed_dict = {x : x_data})
    print(result)

[ 7. 10. 16.]
[ 6.  8. 12.]


### Tensor의 속성

In [15]:
a = tf.constant(1)
b = tf.constant([1,2], dtype = tf.float32)
c = tf.constant([[1,2],[3,4]], dtype = tf.int32)
d = tf.constant(
    [
        [[1.0, 2.0], [3, 4]],
        [[5, 6], [7, 8]]
    ]
)# 3차원

print('a: ', a)
print('b: ', b)
print('c: ', c)
print('d: ', d)

a:  Tensor("Const_10:0", shape=(), dtype=int32)
b:  Tensor("Const_11:0", shape=(2,), dtype=float32)
c:  Tensor("Const_12:0", shape=(2, 2), dtype=int32)
d:  Tensor("Const_13:0", shape=(2, 2, 2), dtype=float32)


### Rank

In [17]:
print("a's rank: ", a._rank())
print("b's rank: ", b._rank())
print("c's rank: ", c._rank())
print("d's rank: ", d._rank())

print("-"*50)

#아래는 텐서로 반환
print("a's rank: ", tf.rank(a))
print("b's rank: ", tf.rank(b))
print("c's rank: ", tf.rank(c))
print("d's rank: ", tf.rank(d))

a's rank:  0
b's rank:  1
c's rank:  2
d's rank:  3
--------------------------------------------------
a's rank:  Tensor("Rank:0", shape=(), dtype=int32)
b's rank:  Tensor("Rank_1:0", shape=(), dtype=int32)
c's rank:  Tensor("Rank_2:0", shape=(), dtype=int32)
d's rank:  Tensor("Rank_3:0", shape=(), dtype=int32)


In [18]:
m,n = c.get_shape()
m,n

(Dimension(2), Dimension(2))

### shape

In [19]:
print("a's shape: ", a.get_shape())
print("b's shape: ", b.get_shape())
print("c's shape: ", c.get_shape())
print("d's shape: ", d.get_shape())

print("-"*50)

#아래는 텐서로 반환
print("a's shape: ", tf.shape(a))
print("b's shape: ", tf.shape(b))
print("c's shape: ", tf.shape(c))
print("d's shape: ", tf.shape(d))

a's shape:  ()
b's shape:  (2,)
c's shape:  (2, 2)
d's shape:  (2, 2, 2)
--------------------------------------------------
a's shape:  Tensor("Shape:0", shape=(0,), dtype=int32)
b's shape:  Tensor("Shape_1:0", shape=(1,), dtype=int32)
c's shape:  Tensor("Shape_2:0", shape=(2,), dtype=int32)
d's shape:  Tensor("Shape_3:0", shape=(3,), dtype=int32)


### dtype

In [22]:
print("a's dtype: ", tf.type(a))
print("b's dtype: ", tf.dtype(b))
print("c's dtype: ", tf.dtype(c))
print("d's dtype: ", tf.dtype(d))

AttributeError: module 'tensorflow' has no attribute 'type'